### ISSUE TITLE
can't fetch playlist over NFS

### ISSUE THREAD

**Issue by kambala-decapitator** [kodi-pvr/pvr.iptvsimple#829] opened 2024-01-30 06:55 UTC
This used to work in Omega alpha, but with the latest Omega nightlies (as well as the latest addon builds) playlist can no longer be fetched. In the log I see:

```
2024-01-30 09:47:09.666 T:46426    info <general>: CAddonMgr::FindAddons: pvr.iptvsimple v21.7.1 installed
2024-01-30 09:47:13.800 T:46690    info <general>: PVR Manager: Starting
2024-01-30 09:47:13.802 T:46715   error <general>: CNFSFile::Open: Unable to open file: 'mnt/multimedia/video/misc/tv.m3u8|connection-timeout=20' error: 'open call failed with "NFS: Lookup of /video/misc/tv.m3u8|connection-timeout=20 failed with NFS3ERR_NOENT(-2)"'
2024-01-30 09:47:13.803 T:46715   error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - Process - unable to connect to: nfs://192.168.1.100/mnt/multimedia/video/misc/tv.m3u8
2024-01-30 09:47:13.803 T:46715    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - ConnectionLost Could not validiate M3U after startup, but ignoring as startup is all we care about.
2024-01-30 09:47:19.319 T:46715   error <general>: CNFSFile::Open: Unable to open file: 'mnt/multimedia/video/misc/tv.m3u8|connection-timeout=20' error: 'open call failed with "NFS: Lookup of /video/misc/tv.m3u8|connection-timeout=20 failed with NFS3ERR_NOENT(-2)"'
<last line repeats>
```

the playlist seems fine on the server:
```
> ll /mnt/multimedia/video/misc
total 128K
-rwxrwxrwx 1 kambala kambala 260 Jun 18  2023 tv.m3u8*

> cat /mnt/multimedia/video/misc/tv.m3u8
#EXTM3U
#EXTINF:-1,BridgeTV Deluxe
udp://@239.255.0.74:5500
#EXTINF:-1,BridgeTV Classic
udp://@239.255.0.240:5500
#EXTINF:-1,BridgeTV Hits
udp://@239.255.0.201:5500
#EXTINF:-1,Муз ТВ
udp://@239.255.0.46:5500
#EXTINF:-1,1HD-Music
udp://@239.255.0.203:5500
```

macOS Sonoma 14.2.1

**Comment by phunkyfish** [comment] 2024-01-30 22:10
The cause of this is likely in kodi and not the addon. We simply use the addon API to s any url

**Comment by phunkyfish** [comment] 2024-02-14 15:16
Fixed by https://github.com/kodi-pvr/pvr.iptvsimple/pull/831/commits/dba8a368865e27394a3fdbf4e5f2c253d942acf5 in PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/831

**Closed as completed by phunkyfish** 2024-02-14 15:16 UTC
