### ISSUE TITLE
Timeshift VOD

### ISSUE THREAD

**Issue by m4f1j0z0** [kodi-pvr/pvr.iptvsimple#207] opened 2018-11-01 11:10 UTC
My IPTV Provider has a large VOD library.

The Simple IPTV addon reports to Kodi that Pause/Rewind/Fast Forward should be disabled, which makes it impossible to timeshift the VOD movies.

If this something you could fix?

**Comment by arthur-liberman** [comment] 2018-11-03 23:33
From what I can tell, it depends on the way that VOD is implemented on the server-side of your IPTV provider. I've been working on something very similar for some time now, the archive feature.
There's nothing official yet, but I think that things are moving in the right direction, and it is something that Team Kodi is looking into.
https://forum.kodi.tv/showthread.php?tid=337062

**Comment by phunkyfish** [comment] 2019-09-21 14:49
Duplicate of: https://github.com/kodi-pvr/pvr.iptvsimple/issues/273

**Closed** 2020-04-16 21:39 UTC
Labels: duplicate, feature request
