### ISSUE TITLE
rapidxml patch fails

### ISSUE THREAD

**Issue by freebs65** [kodi-pvr/pvr.iptvsimple#228] opened 2019-03-10 14:14 UTC
I've tried on 2 systems one arch x86_64 the other rasbian armhf
Fails on both.. 

[  6%] Performing patch step for 'rapidxml'
(Stripping trailing CRs from patch; use --binary to disable.)
patching file rapidxml.hpp
Hunk #1 FAILED at 382 (different line endings).
Hunk #2 FAILED at 549 (different line endings).
Hunk #3 FAILED at 634 (different line endings).
3 out of 3 hunks FAILED -- saving rejects to file rapidxml.hpp.rej
CMakeFiles/rapidxml.dir/build.make:101: recipe for target 'build/rapidxml/src/ra
make[2]: *** [build/rapidxml/src/rapidxml-stamp/rapidxml-patch] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/rapidxml.dir/all' failed
make[1]: *** [CMakeFiles/rapidxml.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by micahg** [comment] 2019-04-14 23:32
I get this too on my Ubuntu 18.10 machine.

**Comment by micahg** [comment] 2019-04-21 12:13
This is actually a duplicate of https://github.com/kodi-pvr/pvr.iptvsimple/issues/215

**Comment by phunkyfish** [comment] 2019-08-15 22:27
Fixed by https://github.com/kodi-pvr/pvr.iptvsimple/pull/216

**Closed as completed by phunkyfish** 2019-08-15 22:27 UTC
