### ISSUE TITLE
No show channel groups & No show three-digit number

### ISSUE THREAD

**Issue by TangBaohua** [kodi-pvr/pvr.iptvsimple#724] opened 2023-03-20 16:52 UTC
KODI 19.X
PVR IPTV Simple Client 19.3
 No show channel groups & No show three-digit number
![NewChannelGroup](https://user-images.githubusercontent.com/11957114/226411095-ebfd04cc-1418-4464-af89-47b5fdf507d6.jpg)
![OldChannelGroup](https://user-images.githubusercontent.com/11957114/226411110-9ff16c22-1c4b-43f8-9f3e-760cddc32e2c.jpg)

the channel number cannot be displayed with three digits
![99](https://user-images.githubusercontent.com/11957114/226411759-8f5fca74-0d27-4e0a-b479-4c63a25e9f39.jpg)

![100](https://user-images.githubusercontent.com/11957114/226411779-5daed488-f31f-431f-8dc2-8f823de6171b.jpg)

**Comment by phunkyfish** [comment] 2023-03-20 19:12
What skin are you using?

BTW, Kodi 19 is EOL now. Does the same issue happen with Kodi 20?

**Comment by TangBaohua** [comment] 2023-03-21 06:22
![20230321134629](https://user-images.githubusercontent.com/11957114/226527804-a5029716-8da0-476c-85b3-cc540e9df6e1.jpg)
![20230321135010](https://user-images.githubusercontent.com/11957114/226528278-cd09d981-a53a-4b04-8471-bdf8f61cbc75.jpg)
![20230321135040](https://user-images.githubusercontent.com/11957114/226528291-41a67abe-4503-417d-ac28-e5c83450fb40.jpg)

It seems that I have found the reason, I am not using the original skin, and the problem does not appear when I switch back to the original skin.
The reason why Estuary Plus is used is because the original skin poster wall does not display the movie name.
I haven't tried KODI 20, it's probably the same。

**Comment by ksooo** [comment] 2023-03-21 06:46
> The reason why Estuary Plus is used is because the original skin poster wall does not display the movie name.

Please report the issue(s) to the author of your skin. Estuary Plus is neither provided nor maintained by Team Kodi.

**Comment by phunkyfish** [comment] 2023-03-21 08:33
Working as intended. Closing.

**Closed as completed by phunkyfish** 2023-03-21 08:33 UTC
