### ISSUE TITLE
Streams are not played since at least Kodi 18.1

### ISSUE THREAD

**Issue by palasinio** [kodi-pvr/pvr.iptvsimple#350] opened 2020-04-07 21:25 UTC
Hello,

last weekend I tried to add my local coolstream neutrino tv box to Kodi 18.6 using your plugin. Evereything seemed to work fine. The channels are listed, EPG is shown, but streams are not played.
![kodiipty](https://user-images.githubusercontent.com/31258581/78720315-c4291900-7925-11ea-8a92-6dcb372a2264.png)
Networktraffic is showing that the stream is transferred from the tv box to kodi.
Later Kodi versions didn't made a difference while a public internet stream is played.
After some testing I discovered that these streams are played at least with Kodi 18.1.

I wans't able to discover something in the logs, exept that ffmpeg maybe closing the session too early?

[kodi_18.6.nok.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4447034/kodi_18.6.nok.log)
[kodi_18.1.ok.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4447036/kodi_18.1.ok.log)

Do you have an idea?

Regards,

Edit: This behaviour is identical on Windows 10 or a Fire TV Stik

**Comment by phunkyfish** [comment] 2020-04-07 21:59
Very strange the handling for a TS file must have changed between 18.1. and 18.6.

Out of curiosity are you able to try Kodi 19 from a nightly build?

BTW I doubt this is an addon issue. Most likely it's Kodi.

**Comment by lymon66** [comment] 2020-04-08 07:54
Same problem here.
IPTV Video Streams from tvheadend no longer play. Audio only channels (Radio) still work
Tried different versions of Kodi and the issue starts with Kodi 18.4 and later 
(With 18.3 videostreams still play fine)

**Comment by phunkyfish** [comment] 2020-04-08 11:00
Are you both using the latest version of TVHeadend?

**Comment by lymon66** [comment] 2020-04-08 12:07
I'm using tvheadend version v4.3-1751~gc54f303c6 and video streams are encoded to H264 - MP4 using ffmpeg version N-94089-gbc3306fd5b 

Streams play fine in other (non Kodi) players, eg. VLC and IPTV apps for Android

**Comment by phunkyfish** [comment] 2020-04-08 14:56
Here's is the list of 18.4 changes:

https://github.com/xbmc/xbmc/milestone/127?closed=1

**Comment by palasinio** [comment] 2020-04-10 13:00
@phunkyfish Hi, yes, I tested Kodi 18.7 and 19 - with the same result.
As I can find in the change log, ffmpeg changed and another entry affected TS.
As you can see, the stream transfers to Kodi but is simply not displayed.
But I didn‘t find a related entry in the logs, so I don‘t have anything to open an issue @Kodi.

Edit: I use Neutrino HD on a settop box.

Oh, another Point is, that the setting to use channel numbers since a custom value doesn‘t work.

**Comment by palasinio** [comment] 2020-04-10 13:37
PS: Mayb this one has to do with it?
https://github.com/xbmc/xbmc/issues/16441
or this one?
https://forum.kodi.tv/showthread.php?tid=343281

**Comment by phunkyfish** [comment] 2020-04-10 13:41
Can you try it on Kodi 19 with inputstream.ffmpegdirect?

You just need to set a KODIPROP before the M3U entry in your channels file.

So if it’s a TS stream then add:

```
#KODIPROP:inputstreamclass=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
```

**Comment by palasinio** [comment] 2020-04-11 19:59
@phunkyfish: this way?

```
#KODIPROP:inputstreamclass=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
#EXTM3U
#EXTINF:-1 tvg-id="41ba4012b5c" tvg-name="Das Erste HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/41ba4012b5c.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",Das Erste HD
http://192.168.0.35:31339/id=4298041ba4012b5c
#EXTINF:-1 tvg-id="43700662b66" tvg-name="ZDF HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700662b66.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF HD
http://192.168.0.35:31339/id=43d8043700662b66
```

Nope, not working - sorry. Kodi 19 from today - the behaviour ist th same: You can see in ressource monitor, that the stream ist transferring.

**Comment by palasinio** [comment] 2020-04-11 22:38
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4465571/kodi.log)

**Comment by phunkyfish** [comment] 2020-04-17 08:21
@palasinio can you confirm it works in 18.3 and not 18.4?

Also, can some give me access to a test stream? You can PM me on forum with details of you want.

**Comment by palasinio** [comment] 2020-04-18 22:58
@phunkyfish: Hi, yes I can confirm it works on 18.1, 18.2, 18.3 and not 18.4. Right now I downloaded 18.2, 18.3 and 18.4 and tested a fresh installation.
But I have no idea, how I should present a stream to you? I guess my settop box to survive 2 minutes after redirecting the port...
PS: If you copy the link to i.e. "VLC", the stream is played.

**Comment by phunkyfish** [comment] 2020-04-20 14:27
There are 2 commits in that release that could be causing the issue (earliest to latest):

- https://github.com/xbmc/xbmc/commit/9a6a4ec80743de6bae16e601d80db73e0b4dfaa3 ([VideoPlayer] Load program from stream property without using streaminfo - backport)
- https://github.com/xbmc/xbmc/commit/0338e992ff63acb598b71df1a9bfb8535ee42d53 ([VideoPlayer] Fix TS resume point, related to PR16314 - backport)

But I would need to somehow to get access to the stream to figure out where the issue might be. Do you have a VPN locally I could connect to or could you record the stream somehow? Bear in mind it would have to be an exact recording, i.e. no conversion taking place when recorded.

**Comment by phunkyfish** [comment] 2020-04-20 16:47
> @phunkyfish: this way?
> 
> ```
> #KODIPROP:inputstreamclass=inputstream.ffmpegdirect
> #KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
> #EXTM3U
> #EXTINF:-1 tvg-id="41ba4012b5c" tvg-name="Das Erste HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/41ba4012b5c.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",Das Erste HD
> http://192.168.0.35:31339/id=4298041ba4012b5c
> #EXTINF:-1 tvg-id="43700662b66" tvg-name="ZDF HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700662b66.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF HD
> http://192.168.0.35:31339/id=43d8043700662b66
> ```
> 
> Nope, not working - sorry. Kodi 19 from today - the behaviour ist th same: You can see in ressource monitor, that the stream ist transferring.

Just curious. Did you install inputstream.ffmpegdirect? I think I forgot to mention that you need to install it. Apologies.

It will be under `VideoPlayer inputstream` in the install addons menu.

(You might need to get the latest kodi build)

**Comment by palasinio** [comment] 2020-04-21 20:56
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4512574/kodi.log)
@phunkyfish 
> But I would need to somehow to get access to the stream to figure out where the issue might be. Do you have a VPN locally I could connect to or could you record the stream somehow? Bear in mind it would have to be an exact recording, i.e. no conversion taking place when recorded.

I did a copy of the straeam with VLC this way:
`:sout=#duplicate{dst=file{dst=C:\\\\Users\\\\user\\\\Desktop\\\\stream.mp4,no-overwrite},dst=display} :sout-all :sout-keep`
Send it in your inbox.
But this one is working from within video section or as file in the .m3u within your plugin.
Still thinking about how to let you access my settop box.

> Just curious. Did you install inputstream.ffmpegdirect? I think I forgot to mention that you need to install it. Apologies.
Of course not ;) But I made it up now.
It still seams to select the default player:
```
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerCoreFactory::GetPlayers(http://192.168.0.35:31339/id=43d8043700666d6b)
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: system rules
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: matches rule: system rules
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: streams
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: matches rule: streams
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: aacp/sdp
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: mp2
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: dvd
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: discimage
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: nsv
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: radio
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
2020-04-21 22:41:56.915 T:1316    DEBUG <general>: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
```

**Comment by palasinio** [comment] 2020-04-21 21:14
@phunkyfish: Damn! :)

I didn't realized that I had to extend the .m3u file for every channel like this:
```
#EXTM3U
#KODIPROP:inputstreamclass=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
#EXTINF:-1 tvg-id="41ba4012b5c" tvg-name="Das Erste HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/41ba4012b5c.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",Das Erste HD
http://192.168.0.35:31339/id=4298041ba4012b5c
#KODIPROP:inputstreamclass=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
#EXTINF:-1 tvg-id="43700662b66" tvg-name="ZDF HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700662b66.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF HD
http://192.168.0.35:31339/id=43d8043700662b66
#KODIPROP:inputstreamclass=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
#EXTINF:-1 tvg-id="191270fa08f" tvg-name="ZDF_neo HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/191270fa08f.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF_neo HD
http://192.168.0.35:31339/id=4f180191270fa08f
#KODIPROP:inputstreamclass=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
#EXTINF:-1 tvg-id="6f270f2b91" tvg-name="KiKA HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/6f270f2b91.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",KiKA HD
http://192.168.0.35:31339/id=2218006f270f2b91
#KODIPROP:inputstreamclass=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t#EXTINF:-1 tvg-id="43700666d6b" tvg-name="ZDFinfo" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700666d6b.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDFinfo
http://192.168.0.35:31339/id=43d8043700666d6b
```
I thought one time at the beginning of the file is enough.
This way it works!

So do you see a way how your plugin can handle this with a dynamic http://...m3u?

**Comment by phunkyfish** [comment] 2020-04-21 21:17
Cool that it works!

How do you mean dynamic m3u?

**Comment by phunkyfish** [comment] 2020-04-21 21:18
@lymon66 can you also try ffmpegdirect?

**Comment by palasinio** [comment] 2020-04-21 21:29
@phunkyfish do you still need access to a stream? How can I contact you for URL?

I configure your plugin with
`http://192.168.0.35/control/xmltv.m3u`

and this returns (cut):
```
#EXTM3U
#EXTINF:-1 tvg-id="41ba4012b5c" tvg-name="Das Erste HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/41ba4012b5c.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",Das Erste HD
http://192.168.0.35:31339/id=4298041ba4012b5c
#EXTINF:-1 tvg-id="43700662b66" tvg-name="ZDF HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700662b66.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF HD
http://192.168.0.35:31339/id=43d8043700662b66
#EXTINF:-1 tvg-id="191270fa08f" tvg-name="ZDF_neo HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/191270fa08f.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF_neo HD
http://192.168.0.35:31339/id=4f180191270fa08f
#EXTINF:-1 tvg-id="6f270f2b91" tvg-name="KiKA HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/6f270f2b91.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",KiKA HD
http://192.168.0.35:31339/id=2218006f270f2b91
#EXTINF:-1 tvg-id="43700666d6b" tvg-name="ZDFinfo" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700666d6b.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDFinfo
http://192.168.0.35:31339/id=43d8043700666d6b
```
This "dynamically" changes with the "favorites" on my box.

so "something" (your plugin?) maybe could fit in the necessary
```
#KODIPROP:inputstreamclass=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
```
lines per channel?

PS: Start the channels with number xy is still useless; they always start with "1".

**Comment by phunkyfish** [comment] 2020-04-21 21:45
> @phunkyfish do you still need access to a stream? Hoy can I contact you for URL?

You can just send me a PM on the kodi forum. Yes, still send me a url as it would be good to fix this in kodi.

> 
> I configure your plugin with
> `http://192.168.0.35/control/xmltv.m3u`
> 
> and this returns (cut):
> 
> ```
> #EXTM3U
> #EXTINF:-1 tvg-id="41ba4012b5c" tvg-name="Das Erste HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/41ba4012b5c.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",Das Erste HD
> http://192.168.0.35:31339/id=4298041ba4012b5c
> #EXTINF:-1 tvg-id="43700662b66" tvg-name="ZDF HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700662b66.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF HD
> http://192.168.0.35:31339/id=43d8043700662b66
> #EXTINF:-1 tvg-id="191270fa08f" tvg-name="ZDF_neo HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/191270fa08f.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF_neo HD
> http://192.168.0.35:31339/id=4f180191270fa08f
> #EXTINF:-1 tvg-id="6f270f2b91" tvg-name="KiKA HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/6f270f2b91.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",KiKA HD
> http://192.168.0.35:31339/id=2218006f270f2b91
> #EXTINF:-1 tvg-id="43700666d6b" tvg-name="ZDFinfo" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700666d6b.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDFinfo
> http://192.168.0.35:31339/id=43d8043700666d6b
> ```
> 
> This "dynamically" changes with the "favorites" on my box.
> 
> so "something" (your plugin?) maybe could fit in the necessary
> 
> ```
> #KODIPROP:inputstreamclass=inputstream.ffmpegdirect
> #KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
> ```
> 
> lines per channel?

Possibly. I could add a default ffmpeg and an mime type setting to the addons advanced settings. What happens if you add the ffmpegdirect props but omit the mime_type lines? It may just load slower but still work.



> 
> PS: Start the channels with number xy is still useless; they always start with "1".

Can you open a separate issue and add an M3U to it? Then I can test loading it.

**Comment by palasinio** [comment] 2020-04-21 22:01
> Possibly. I could add a default ffmpeg and an mime type setting to the addons advanced settings. What happens if you add the ffmpegdirect props but omit the mime_type lines? It may just load slower but still work.

Yep, this still works :)

**Comment by palasinio** [comment] 2020-04-21 22:14
PS: Is there a way to get this work /w Kodi 18.6?

**Comment by phunkyfish** [comment] 2020-04-22 06:01
> PS: Is there a way to get this work /w Kodi 18.6?

If you can send me a test stream I can try and fix it on kodi 18.

**Comment by palasinio** [comment] 2020-04-22 13:56
> If you can send me a test stream I can try and fix it on kodi 18.

You are hard to contact; l‘m not (yet) allowed to send private messages in the Kodi forum.

**Comment by phunkyfish** [comment] 2020-04-22 14:00
Is your username `palace` on the forum?

**Comment by palasinio** [comment] 2020-04-22 14:01
Yep!

**Comment by phunkyfish** [comment] 2020-04-22 15:04
You should be able to PM now.

**Comment by lymon66** [comment] 2020-04-23 06:29
> 
> 
> @lymon66 can you also try ffmpegdirect?

Tried it on a testbuild of Kodi 19 (Libreelec 9.80 on a RPI), with ffmpegdirect addon installed and enabled within iptv addon, but still no video unfortunately.
I do get an error about an unsupported stream in the log now:

2020-04-23 05:53:53.386 T:437  NOTICE: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: http://192.168.10.10:9981/stream/channelid/369032226?profile=omx
2020-04-23 05:54:04.593 T:437  NOTICE: Previous line repeats 1 times.
2020-04-23 05:54:04.594 T:437  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All%20channels/pvr.iptvsimple_665313884.pvr
2020-04-23 05:54:04.614 T:569  NOTICE: Creating InputStream
2020-04-23 05:54:04.705 T:437  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All%20channels/pvr.iptvsimple_665313884.pvr
2020-04-23 05:54:15.498 T:569  NOTICE: Creating Demuxer
2020-04-23 05:54:16.755 T:569  NOTICE: Opening stream: 0 source: 256
2020-04-23 05:54:16.756 T:569 WARNING: OpenStream - Unsupported stream 0. Stream disabled.
2020-04-23 05:54:16.756 T:569  NOTICE: Opening stream: 1 source: 256
2020-04-23 05:54:16.757 T:569  NOTICE: Finding audio codec for: 86018
2020-04-23 05:54:16.767 T:569  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-04-23 05:54:16.767 T:569  NOTICE: Creating audio thread
2020-04-23 05:54:16.779 T:569 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
2020-04-23 05:54:16.781 T:571 WARNING: Previous line repeats 1 times.
2020-04-23 05:54:16.787 T:571  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-04-23 05:54:17.795 T:569  NOTICE: Creating InputStream
2020-04-23 05:54:28.706 T:569  NOTICE: Creating Demuxer
2020-04-23 05:54:29.133 T:569  NOTICE: Opening stream: 0 source: 256
2020-04-23 05:54:29.133 T:569 WARNING: OpenStream - Unsupported stream 0. Stream disabled.
2020-04-23 05:54:29.134 T:569  NOTICE: Opening stream: 1 source: 256
2020-04-23 05:54:29.135 T:569  NOTICE: Finding audio codec for: 86018
2020-04-23 05:54:29.138 T:569  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac



FFMPEG stream information:

STREAM 0:
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=High
codec_type=video
codec_time_base=0/2
codec_tag_string=[27][0][0][0]
codec_tag=0x001b
width=480
height=256
coded_width=480
coded_height=256
has_b_frames=0
sample_aspect_ratio=N/A
display_aspect_ratio=N/A
pix_fmt=yuv420p
level=40
color_range=unknown
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
field_order=progressive
timecode=N/A
refs=1
is_avc=false
nal_length_size=0
id=0x100
r_frame_rate=25/1
avg_frame_rate=0/0
time_base=1/90000
start_pts=127920
start_time=1.421333
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0

STREAM 1
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_time_base=1/48000
codec_tag_string=[15][0][0][0]
codec_tag=0x000f
sample_fmt=fltp
sample_rate=48000
channels=1
channel_layout=mono
bits_per_sample=0
id=0x101
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/90000
start_pts=126000
start_time=1.400000
duration_ts=N/A
duration=N/A
bit_rate=58125
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
TAG:language=eng


Also very weird, I have an Amlogic box with Coreelec 9.2.2 (Kodi 18.6) installed and on this box video plays fine using the iptv addon...I'm very confused now.

So far I have tested:
RPI (libreelec/openelec):  Kodi 18.4 and later: no video
Android (kodi): Kodi 18.4 and later: no video
Amlogic (coreelec 9.2.2): Kodi 18.6 : working fine

**Comment by phunkyfish** [comment] 2020-04-23 07:09
Did you add the kodi props for ffmpegdirect correctly?

Please give an example of the M3U file also.

Please do so and then lost a full debug log using a paste site for kodi 19.

Also, anyway you can get me a test stream also?

**Comment by palasinio** [comment] 2020-04-23 08:59
> You should be able to PM now.

You have mail ;)

**Comment by phunkyfish** [comment] 2020-04-23 10:39
> > You should be able to PM now.
> 
> You have mail ;)

Cool, will look at it as soon as I can.

**Comment by phunkyfish** [comment] 2020-04-23 11:03
Found something interesting.

Can you try this:

```
#EXTM3U
#KODIPROP:mimetype=video/mp2t
#EXTINF:-1 tvg-id="41ba4012b5c" tvg-name="Das Erste HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/41ba4012b5c.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",Das Erste HD
http://192.168.0.35:31339/id=4298041ba4012b5c
#KODIPROP:mimetype=video/mp2t
#EXTINF:-1 tvg-id="43700662b66" tvg-name="ZDF HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700662b66.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF HD
http://192.168.0.35:31339/id=43d8043700662b66
```

When I tried this which is simply passing the mime type to Kodi 19 it worked. Would be interested to the see the results on 18.3, 18.4, 18.6 @palasinio 

@lymon66 could you also try with this? Although I'm beginning to suspect you may have a different issue (possibly)

**Comment by palasinio** [comment] 2020-04-23 21:03
> Can you try this:
> ```
> #EXTM3U
> #KODIPROP:mimetype=video/mp2t
> #EXTINF:-1 tvg-id="41ba4012b5c" tvg-name="Das Erste HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/41ba4012b5c.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",Das Erste HD
> http://192.168.0.35:31339/id=4298041ba4012b5c
> #KODIPROP:mimetype=video/mp2t
> #EXTINF:-1 tvg-id="43700662b66" tvg-name="ZDF HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700662b66.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF HD
> http://192.168.0.35:31339/id=43d8043700662b66
> ```
> When I tried this which is simply passing the mime type to Kodi 19 it worked. Would be interested to the see the results on 18.3, 18.4, 18.6 @palasinio

Right! This one worked with Kodi 19, but not with Kodi 18.6. I didn't test 18.3, cause this is still working.

**Comment by phunkyfish** [comment] 2020-04-23 22:45
> 
> Right! This one worked with Kodi 19, but not with Kodi 18.6. I didn't test 18.3, cause this is still working.

Interesting. I will try to fix kodi 19 first. FYI this could take several days to figure out.

**Comment by Rocket200** [comment] 2020-04-26 14:36
> > Can you try this:
> > ```
> > #EXTM3U
> > #KODIPROP:mimetype=video/mp2t
> > #EXTINF:-1 tvg-id="41ba4012b5c" tvg-name="Das Erste HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/41ba4012b5c.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",Das Erste HD
> > http://192.168.0.35:31339/id=4298041ba4012b5c
> > #KODIPROP:mimetype=video/mp2t
> > #EXTINF:-1 tvg-id="43700662b66" tvg-name="ZDF HD" tvg-logo="http://192.168.0.35/share/tuxbox/neutrino/icons/logo/43700662b66.png" radio="" group-prefix="zee2" group-title="Meine Favoriten",ZDF HD
> > http://192.168.0.35:31339/id=43d8043700662b66
> > ```
> > 
> > 
> > When I tried this which is simply passing the mime type to Kodi 19 it worked. Would be interested to the see the results on 18.3, 18.4, 18.6 @palasinio
> 
> Right! This one worked with Kodi 19, but not with Kodi 18.6. I didn't test 18.3, cause this is still working.

on what System this work for you ? 
I try with FireTV4K and newest Kodi19 but not work.

**Comment by palasinio** [comment] 2020-04-26 15:22
@Rocket200: I have Windows and FireTV 4K.
What are you streaming from and have you edited the m3u file and tested the different KodiProbs shown in the thread above?

**Comment by Rocket200** [comment] 2020-04-26 15:30
streaming from Tank NI Nightly from today
and i try the edited m3u
but not work for me with FireTV4K and Kodi19 from today 

can we talk somewhere (discord,or..)
Nullinga my Nick there

**Comment by palasinio** [comment] 2020-04-26 15:47
@Rocket200: Have you tried with Videoplayer Inputstream plugin and 
```
#KODIPROP:inputstreamclass=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t
#EXTINF:-1 ....
```
I have to admit, that I didn‘t tested FireTV Stick right now, cause its on the family tv.
Is the same setup of Kodi working /w windows?

**Comment by Rocket200** [comment] 2020-04-26 15:54
yes i try it already on Firetv4k not working

**Comment by palasinio** [comment] 2020-04-26 16:02
Oh! So if it works with windows maybe there is a different issue. Is it working with Kodi 18.3?
Can you send a debug log?

**Comment by Rocket200** [comment] 2020-04-26 16:22
I need to go back to my old working kodi19 from April 2019 :(

here is a log https://pastebin.com/pvhpaTgb
but I dont know I make something wrong or not

**Comment by Rocket200** [comment] 2020-04-28 08:47
ok now it works with inputstream and mimetype 

https://paste.kodi.tv/aboporonor.kodi
https://paste.kodi.tv/kokacoyexe.kodi

but stream can not watch to much Artefacts 
i think all new Android Kodi19 have more bugs und problems.

not same the Kodi19 Build from April2019
here is all fine.

**Comment by phunkyfish** [comment] 2020-04-28 10:46
This is because ffmpeg is handling the stream directly.

Once the issue is fixed it should work again the way you expect. It could take some time to get this fixed.

**Comment by Rocket200** [comment] 2020-04-28 11:21
is this an new bug?
anywhere can read about?
and who fix this problem?

i make later from working kodi19 (april2019) a logfile in this Build everything works better than the new nightlys

**Comment by phunkyfish** [comment] 2020-04-28 11:49
Please be patient. When I have an update I will post it here. Until then you will have to wait.

**Comment by phunkyfish** [comment] 2020-04-28 11:50
Asking me constantly is it fixed yet or any update just clutters the issue thread for anyone trying to understand what’s going on.

**Comment by phunkyfish** [comment] 2020-05-05 13:40
@palasinio can you test this build including the fix for leia? It's for Win64

https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20200505-b2f11032-fix-ts-stream-leia-x64.exe

**Comment by Rocket200** [comment] 2020-05-05 14:46
have you a testbuild for Android too?
can i test it on Android?

**Comment by phunkyfish** [comment] 2020-05-05 15:36
ARMv7: https://jenkins.kodi.tv/job/Android-ARM/17952/artifact/kodi-20200505-75c9030c-PR17805-merge-armeabi-v7a.apk
ARM64: https://jenkins.kodi.tv/job/Android-ARM64/14576/artifact/kodi-20200505-75c9030c-PR17805-merge-arm64-v8a.apk

**Comment by lymon66** [comment] 2020-05-05 18:25
Can confirm that the testbuilds for X64 and Android ARMv7 fixed the problem (for me at least)

**Comment by Rocket200** [comment] 2020-05-05 19:32
here same on FireTV4K it works with the testbuild Kodi18.6 with IPTV Simple 3.9.8 👌

you have a testbuild Kodi19 with new IPTV Simple Version soon too?

**Comment by phunkyfish** [comment] 2020-05-05 19:35
No, but it's identical and I was able to test it using @palasinio's supplied stream.

Kodi 19 PR will be merged tomorrow and Kodi 18 in a few days.

**Comment by Rocket200** [comment] 2020-05-05 19:44
Thank you @phunkyfish 🙏

@palasinio you have same problem with Channels/Groups with umlauts (ä ö ü) ?

**Comment by Rocket200** [comment] 2020-05-06 19:37
https://jenkins.kodi.tv/job/Android-ARM/17968/

now it works with Kodi19 👌

**Comment by I-Cat** [comment] 2020-05-06 22:41
okay thnx how do we close solved threads?

**Comment by ghost** [comment] 2020-05-06 22:41
> No, but it's identical and I was able to test it using @palasinio's supplied stream.
> 
> Kodi 19 PR will be merged tomorrow and Kodi 18 in a few days.

okay thnx how do we close solved threads?

**Comment by phunkyfish** [comment] 2020-05-07 06:26
The thread author clicks the close button.

**Comment by palasinio** [comment] 2020-05-07 22:02
@phunkyfish 
> @palasinio can you test this build including the fix for leia? It's for Win64
> 
> https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20200505-b2f11032-fix-ts-stream-leia-x64.exe

Hi, I can confirm that your "leia" build and latest Kodi 19 did the trick!
With Kodi 19 it doesn't matter /w or /wo "Inputstream FFmpeg Direct" plugin - it works.

I haven't checked on my Fire TV Stick, but I am confident :)

Thank you so very much!

**Closed as completed** 2020-05-07 22:03 UTC
Labels: bug
