### ISSUE TITLE
[feature] Add optional stream URL for each programme

### ISSUE THREAD

**Issue by prbdias** [kodi-pvr/pvr.iptvsimple#123] opened 2017-05-06 00:26 UTC
Would be nice if we could have the ability to pass a stream URL for a given programme so the user could watch a specific programme from the past.

**Comment by Jalle19** [comment] 2017-08-06 18:31
This is on the roadmap for the PVR API, but since this depends on changes to the API I'm going to close this issue until it's even possible to implement it.

**Comment by prbdias** [comment] 2017-09-26 22:41
@Jalle19 Aren't the PVR API changes in place now? 
The following changes suggest to me that we are now able to start thinking of this new feature. #155 

@ksooo any thoughts regarding this?

Thanks!

**Comment by Jalle19** [comment] 2017-09-27 04:24
This should indeed be possible now

**Comment by vpeter4** [comment] 2017-10-26 10:06
I implemented this feature to play program from the epg and it is working like a charm. To see the content from the past I need to pass time parameter with basic url for particular channel. Obviously it is not generic solution because it is closely connected how my stream works.

The only remaining issue I have is seeking because I need to stop playing current stream, change time parameter and play new url. But this is separate issue which seems it is impossible to get it working because kodi doesn't understand this and doesn't provide any mechanism to deal with.

**Comment by prbdias** [comment] 2018-06-11 20:48
@vpeter4 do you have your implementation available somewhere? Would be much appreciated if you could share your implementation so I can give it a try :)

**Comment by vpeter4** [comment] 2018-06-12 05:58
@prbdias: No, it is not available publicly but I send a mail to you.

**Comment by shamanNS** [comment] 2018-06-12 06:14
@vpeter4: Could you also email me? I've tried to implement that feature myself but my knowledge of C++ is inadequate.

**Comment by Sorien** [comment] 2018-06-20 11:36
@vpeter maybe you could make PR, it would be nice to have it for Leia.

**Comment by vpeter4** [comment] 2018-06-20 13:09
@Sorien: I think at least time format should be adjustable in addon settings somehow. I'm using *.......&t=2018-06-19-20-00-00* but other providers are probably using different format. Didn't look much into it...

**Comment by Sorien** [comment] 2018-06-20 14:14
i thought about s/t like 
```xml
<programme>
<url>
http://everythink/what/you/want
<url>
</programme>
```

**Comment by vpeter4** [comment] 2018-09-28 08:15
Guys, I'm using my implementaion to watch shows from EPG for almost a year and it is working great. The only drawback is that seeking doesn't work. I hacked some solution for my personal use but it is not usable for others. That's why my friend look into it and made much progress. Now seeking also works. Currently little limited but he is on a good track. Now there are two streaming services which works (mine and from my friend). That's why I would like to gather some more feedback how other streaming services work.

I have urls like this in M3U8 playlist:
```
http://streaming.server/stream1.m3u8
http://streaming.server/stream2.m3u8
```
To watch something from EPG I need to add time parameter of this show in format
`http://streaming.server/stream.m3u8&t=2018-09-19-20-00-00`
But my friend is using such format
`http://streaming.server/stream.m3u8?utc=1407164412&lutc=1407165000`
it is current time and time from epg.

So I would like to know if anyone can provide some other real use cases. It would help to make universal client.

**Comment by Sorien** [comment] 2018-09-28 11:50
@vpeter4 is there any repository with yours changes? i'd try it, l have callback to python addon so i can use any url format.

**Comment by arthur-liberman** [comment] 2018-10-03 13:00
There is something we're working on, knowing how different IPTV provider format their URLs would be helpful to implementing a proper configuration for this feature.

**Comment by phunkyfish** [comment] 2019-09-21 14:40
Duplicate of: https://github.com/kodi-pvr/pvr.iptvsimple/issues/273

**Closed** 2020-04-16 21:38 UTC
Labels: duplicate, feature request
