### ISSUE TITLE
Mac error

### ISSUE THREAD

**Issue by drtiwarir** [kodi-pvr/pvr.iptvsimple#686] opened 2023-01-29 05:48 UTC
I am using Kodi nexus on Macmini, after recent update, whenever I change a channel (using m3u file) it does not work. I have to quit and play again, then it works.
The same m3u file works smoothly in Nvidia Shield tv with Kodi.
Is there any solution to this issue ?

**Comment by phunkyfish** [comment] 2023-01-29 14:57
Can you try putting some of the channel URLs in `.strm` files and see if they play ok as videos?

**Comment by drtiwarir** [comment] 2023-01-30 10:07
Thanks for your help
I tried what you asked, but the situation remains same, did not work.
As I mentioned previously, channels play well, but if I change a channel it doesn’t work till I exit and come back

**Comment by phunkyfish** [comment] 2023-01-30 12:34
If the channels don’t work in strm files then that means either the problem is in Kodi core (and not anything to do with PVR), or something related to your provider.

**Comment by drtiwarir** [comment] 2023-01-31 09:30
It seems problem is with kodi, I went back to Matrix and it is working well

**Comment by phunkyfish** [comment] 2023-01-31 09:55
Can you try the omega nightlies? They run ffmpeg 5 and might fix the problem.

**Comment by drtiwarir** [comment] 2023-01-31 10:20
Will try tonight

Thanks

**Comment by drtiwarir** [comment] 2023-01-31 10:20
Will try tonight

**Comment by drtiwarir** [comment] 2023-02-08 07:19
I have tried Nightlies, but can't switch channels. Seems Kodi having issues
with Mac

Regards
Ravi

**Comment by phunkyfish** [comment] 2023-02-08 08:09
@fuzzard @kambala-decapitator FYI, as it could be a Mac regression.

**Comment by phunkyfish** [comment] 2023-02-08 08:10
@drtiwarir can you provide a full debug log please?

https://kodi.wiki/view/Log_file/Easy

**Comment by kambala-decapitator** [comment] 2023-02-08 08:20
do you have intel or arm Mac? If ARM, do you use intel or arm builds?

**Comment by drtiwarir** [comment] 2023-02-08 08:24
I will update you with logs and my Mac's processor after I reach home, in 3
hours time
Your support is highly appreciated.

Regards
Ravi

**Comment by drtiwarir** [comment] 2023-02-08 10:13
Please check the attachments. Hope this helps to fix the problem.

Regards
Ravi

**Comment by kambala-decapitator** [comment] 2023-02-08 10:18
@drtiwarir sorry, there're no attachments

**Comment by drtiwarir** [comment] 2023-02-08 10:21
<img width="2048" alt="Screenshot 2023-02-08 at 3 37 19 PM" src="https://user-images.githubusercontent.com/68334674/217502443-515a4c6e-7554-4d46-8eb3-9cd28d8b1a5b.png">
<img width="279" alt="Screenshot 2023-02-08 at 3 40 56 PM" src="https://user-images.githubusercontent.com/68334674/217502515-f42e9203-8f4a-40c0-a199-c37b8117e101.png">

**Comment by kambala-decapitator** [comment] 2023-02-08 10:26
@drtiwarir thanks. But please:

1. enable debug logging: https://kodi.wiki/view/Log_file/Easy
2. upload full log as text (not just SS of small portion), the Log Viewer has such option

**Comment by drtiwarir** [comment] 2023-02-08 10:48
https://paste.kodi.tv/tipuzarene

**Comment by kambala-decapitator** [comment] 2023-02-08 10:58
@drtiwarir thanks, but you still haven't enabled debug logging.

1. enable debug logging by following https://kodi.wiki/view/Log_file/Easy
2. reproduce the issue
3. upload the log

basically just follow all the steps given in the link

**Comment by drtiwarir** [comment] 2023-02-08 11:16
My brain has now stopped working
My apologies

**Comment by drtiwarir** [comment] 2023-02-10 10:22
I have gone back to Kodi Matrix
Everything working well
Thanks for your time and support

Regards
Ravi

**Comment by phunkyfish** [comment] 2023-02-10 13:30
If you do this then whatever the issue is won’t be fixed for other users.

**Comment by drtiwarir** [comment] 2023-02-11 06:49
I understand your point, but I tried my best to help our Kodi community.
And since the Nexus update my entertainment had stopped, I could not relax
watching my favourite tv shows.
I hope you understand the situation.

Regards
Ravi.

**Comment by phunkyfish** [comment] 2023-02-11 12:12
Yes, but you were a single step away from providing the information that would allow us to fix this issue. You simply had to enable debug logging in kodi and produce the log once more.

**Comment by kambala-decapitator** [comment] 2023-02-11 12:17
@phunkyfish could you close the issue as "not planned" instead?

**Comment by phunkyfish** [comment] 2023-02-11 12:17
Done

**Comment by kambala-decapitator** [comment] 2023-02-11 12:30
nothing changed it seems... You need to reopen the issue and then close it with different type.

**Comment by phunkyfish** [comment] 2023-02-11 13:01
Ok, very strange. Done now.

**Closed as not planned** 2023-02-11 13:00 UTC
