### ISSUE TITLE
7.0.0-matrix Kodi 19 Alpha3: loss of EPG data

### ISSUE THREAD

**Issue by Gregsr** [kodi-pvr/pvr.iptvsimple#450] opened 2020-11-16 14:10 UTC
When I play a channel, I lose EPG data (No information available) for this channel only. Data come back when I switch to another channel.
Consequence: I cannot use the catch up function for the played channel.

No issue with Kodi 19 Alpha2

**Comment by phunkyfish** [comment] 2020-11-16 14:37
Can you supply a full debug log please?

**Comment by Gregsr** [comment] 2020-11-16 20:17
Here is https://paste.kodi.tv/janefawego.kodi
EPG data come back when I stop the playing too.

Other issue with EPG, the message "No information available" should be hidden and it is not the case (I checked this option in settings/PVR/EPG).

Thank you

**Comment by phunkyfish** [comment] 2020-11-16 21:57
Sorry, can't help you. You have banned addons installed: plugin.video.vstream 

Please remove the banned addon and provide a fresh "DEBUG" log. But from a glance you try the next nightly build from today or later. There were some EPG fixes in the last couple of weeks.

**Comment by Gregsr** [comment] 2020-11-17 09:37
Sorry, I didn't know.
Here is a log without this addon https://paste.kodi.tv/gihecuresi.kodi . I don't know if it is a DEBUG log. I will try with the last nightly this week.

**Comment by phunkyfish** [comment] 2020-11-17 11:02
No worries.

Still not a debug log. It’s usually ctrl + shift + d to enable debug logging. Then just restart and reproduce the issue.

**Comment by Gregsr** [comment] 2020-11-17 19:30
Here is 
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/5555756/kodi.log)
I reproduced the issue with http://xxx.com:9999/xxx/xxx/22372 and http://xxx.com:9999/xxx/xxx/4692

**Comment by phunkyfish** [comment] 2020-11-18 09:47
I don’t see anything troublesome in your log.

Can you install the latest beta release, clear all the PVR data (in kodi’s PVR settings) and see does it still occur.

**Comment by Gregsr** [comment] 2020-11-20 17:02
Same results with beta1 on Android 32bits but no issue on Win10 with the same settings.

On both OS, the message "No information available" is present for channel without EPG while it should be hidden (Hide labels is checked)

**Comment by phunkyfish** [comment] 2020-11-20 22:01
So only on 32 bit Android. Interesting.

The hide no information labels setting works for me on Mac.

**Comment by phunkyfish** [comment] 2020-12-07 21:21
Once beta2 is out please recheck the EPG issue on Android 32bit. Any way to check what happens on Android 64bit also?

Trying to figure out if it's all of Android affected or just 32bit.

**Comment by Gregsr** [comment] 2020-12-08 20:03
- Beta2 on Android TV 9 32bit and v7.1.0: same issue
- Beta2 on Win7 64bit and v7.1.0: no issue (EPG data are present) but there is an issue with the catch up. I took 3 printscreens:
     1. Before using, no issue
![image](https://user-images.githubusercontent.com/14049971/101528887-209a7780-3990-11eb-850b-9d5eb3f6ef94.png)

     2. The moment when I step back
![image](https://user-images.githubusercontent.com/14049971/101528947-2ee89380-3990-11eb-9c72-5cc211f85dc1.png)

     3. After I stepped back 
![image](https://user-images.githubusercontent.com/14049971/101528994-3d36af80-3990-11eb-9ca6-089d96edd3f4.png)

- No possibility to test on Android 64bit

**Comment by phunkyfish** [comment] 2020-12-08 20:36
That gives us a clue. The very strange number probably means a 64bit value is being forced into a 32bit variable.

Now we just need to figure out where that happens.

@AlwinEsch any idea if this happened during the last inputstream API update somehow or a clue of where to look for it?

**Comment by phunkyfish** [comment] 2020-12-08 21:59
If the change that caused this happened between Alpha2 and Alpha3 that means the offending commit was merged between October 5th and October 31st.

**Comment by phunkyfish** [comment] 2021-04-03 19:42
Resolved.

**Closed as completed by phunkyfish** 2021-04-03 19:42 UTC
