### ISSUE TITLE
iptvsimple not working with latest kodi nightlies

### ISSUE THREAD

**Issue by popcornmix** [kodi-pvr/pvr.iptvsimple#139] opened 2017-07-24 16:16 UTC
This report: https://forum.kodi.tv/showthread.php?tid=298461&pid=2621748#pid2621748
is probably due to https://github.com/xbmc/xbmc/pull/12550

The functions strStreamURL and SwitchChannel were deprecated 18 months ago and have now been removed.
https://forum.kodi.tv/showthread.php?tid=259830

**Comment by popcornmix** [comment] 2017-07-24 16:20
It seems nightlies are using 3.0.2.1. Has this behaviour changed with v3.1.0 ?

**Comment by leleobhz** [comment] 2017-07-25 01:57
Hello,

Version http://forum.kodi.tv/showthread.php?tid=298461&pid=2622019#pid2622019 (0724) does not work. (0722) works - issue reproduced as https://forum.kodi.tv/showthread.php?tid=298461&pid=2621784#pid2621784

**Comment by Jalle19** [comment] 2017-08-06 18:41
Duplicate of #140

**Closed by Jalle19** 2017-08-06 18:41 UTC
