### ISSUE TITLE
Multiple channel with the same tvg-id

### ISSUE THREAD

**Issue by 0xcpy** [kodi-pvr/pvr.iptvsimple#198] opened 2018-10-02 16:11 UTC
When opening a playlist that have multiple channel with the same tvg-id, epg is only shown in one of them

**Comment by nsenica** [comment] 2018-10-18 08:45
Do you mean support for multiple display-name tags in the same channel ? If so, a +1 from me for this.

**Comment by Znuff** [comment] 2019-02-15 20:36
If this is similar to my issue, and how I eventually fixed it - it's probably because some channels have an "SD" version and a "HD" version, but they are essentially the same channel (with the same schedule).

So if you are trying to display the names differently, let's say:

```
#EXTM3U
#EXTINF:1 tvg-id="Antena1" tvg-name="Antena1" tvg-logo="https://[redacted].eu/logo/antena1.png" group-title="ROMANIA",Antena 1
https://[redacted]/6406
#EXTINF:1 tvg-id="Antena1" tvt=name="Antena1 HD" tvg-logo="https://[redacted].eu/logo/antena1hd.png" group-title="ROMANIA",Antena 1 HD
https://[redacted]/6407
```

It will fail matching the 2nd channel against an XMLTV file that has the ID specified as:

```
  <channel id="Antena1">
    <display-name lang="ro">Antena 1</display-name>
  </channel>
```

My only solution to this was to completely remove `tvg-name` from the `M3U` list.

See #221.

**Comment by mrsharpey** [comment] 2019-05-10 14:09
I experience this issue too. Wasn't the case on previous versions. I get the EPG populated on 1 of the 3 iterations of the same channel only.

Will this issue be looked into? Happy to provide evidence/logs etc.

**Comment by hoshsadiq** [comment] 2019-05-29 23:55
I think I may have just stumbled upon this issue. The issue doesn't seem to be multiple channels point to one EPG channel, but it seems to be casing.

E.g. in my case, it would match `Channel.us`, whereas it wouldn't match against `channel.us` so hand to end up writing an automated solution to change `tvg-id` to be the correct one.

**Comment by mrsharpey** [comment] 2019-05-30 10:45
Hi, @hoshsadiq 

I found that if the channel names aren't ALL exact naming case wise, or if 'tvg-id' is 'tvg-ID'  (I had both in my case), the issue occurs. If you run a script against the m3u file to ensure all naming conventions match, all is fine.

**Comment by Evandro1975** [comment] 2019-05-30 11:09
The tvg-ID problem exists and there Is another issue number (#195) opened about that

**Comment by mrsharpey** [comment] 2019-05-30 13:27
@Evandro1975 Ah yeah, sorry. Seems like a global make lowercase is required throughout and that'll close both these issues.

I've basically done this with a Python task on my RaspberryPi, which then hosts the modified m3u file on a SAMBA shared that's picked up by Kodi.

**Comment by Evandro1975** [comment] 2019-05-30 15:49
The problem is that the 90% of people that use Kodi and this add on are simple users. Nobody of them known what's the meaning of the word "script" or "task" and also there are thousands of providers that build automatically their m3u for that users, and it's impossible to explain them that it's important to writer the tvg-id tag in lowercase.

**Comment by hoshsadiq** [comment] 2019-05-30 19:32
@Rechi could we get a fix for this? I just tried writing it, but I don't know much C++ and I can't seem to get it built either, and I'm 99% sure my code was wrong. Should be a simple `tolower()` on `strLine` in `PVRIptvData::ReadMarkerValue` before doing the initial find (would fix #195). Then `tolower()` in `PVRIptvData::FindChannel` for all three equal checks (for this issue). I didn't find anywhere else where this would be necessary, but then like I said, I'm unable to build it so unable to test.

**Comment by KDanielK** [comment] 2019-07-02 21:09
Is anyone working on a fix for this issue? tvg-id="AAA.xy" should be matched against tvg-id="aaa.xy" but this is not happening right now

**Comment by phunkyfish** [comment] 2019-08-27 15:36
Support for multiple display-names and case insensitive match in #269 

Note you will stll need to remove tvg-name from the M3U list.

EDIT: fix was easier than I thought. Also fixed in above PR.

**Comment by phunkyfish** [comment] 2019-09-05 05:48
And #275

**Closed by phunkyfish** 2019-09-05 05:48 UTC
Labels: In PR, bug
